option Folder.1.MS "1"
option MsgService.ms1.Port "143"
option MsgService.ms2.Hostname "news.bangor.ac.uk"
option MsgService.ms3.Hostname "Local Workstation"
option MsgService.ms1.Hostname "mailhost"
option General.ExitClean "Prompt"
option MessageGroups.1.inbox.2.Pattern "*read receipt*"
option MsgService.ms1.FolderLocation "~/Mail/"
option MsgService.ms3.FolderLocation ""
option MsgService.ms2.FolderLocation ""
option Folder.1.inbox.Sort "Most Recent Date Sent"
option MessageGroups.1.inbox.IDList "1 2"
option FOLDER.ID "1"
option Folder.1.inbox.ID "1"
option MessageGroups.1.inbox.2.Sort "Most Recent Arrival"
option MsgService.ms2.Port "143"
option MsgService.ms3.FolderPrefix ""
option MsgService.ms1.Type "mail"
option Folder.1.IsSelecting "OFF"
option MessageGroups.1.inbox.1.HideIfEmpty "OFF"
option MsgService.ms3.Userid ""
option MessageGroups.1.inbox.2.Fields "Subject"
option MsgService.ms2.Userid ""
option MsgService.ms1.Name "Post Office"
option MessageGroups.1.inbox.1.Sort "Most Recent Arrival"
option Folder.1.ViewMsgGrps "OFF"
option MessageGroups.1.inbox.2.HideIfEmpty "OFF"
option MsgService.ms2.Type "bboard"
option MessageGroups.1.inbox.1.Fields "Subject"
option MsgService.ms2.Name "News Stand"
option Windows.ScreenWin.Border "0 0 800 600 0 78"
option MessageGroups.1.inbox.2.Name "Read Receipts"
option MsgService.IDList "1 2 3"
option MsgService.ms3.Type "local"
option General.MailAddress "@bangor.ac.uk"
option MessageGroups.1.inbox.1.Pattern "*Phone Message*"
option General.Fullname ""
option Options.Version "40"
option MsgService.ms1.FolderPrefix "~/Mail/"
option MsgService.ms3.Name "Local Folders"
option MsgService.ms1.Userid ""
option WinPosn.Compose.Border "30 49 585 445 Norm"
option MsgService.ms2.FolderPrefix ""
option MessageGroups.1.inbox.1.Name "Phone Messages"
option Timer.Interval "10"
option Folder.1.Name "inbox"
